/*---------------------------------------------------------------------------*\
    F ast           	    | FAST-FC: 
	is the		            | The Open Source Analysis and Simulation Toolbox 
    A nalysis and           | for Fuel Cells
	S imulation		        |
	Toolbox for		        | Copyright 2015, David B. Harvey
	F uel                   |         
	C ells                  |                     
-------------------------------------------------------------------------------
License
	This file is part of FAST-FC.
   
	This file must be included in the main program and it is a violation of
	the license to remove it from the contents or from the 
	main program.

	FAST-FC is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    FAST-FC is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with FAST-FC.  If not, see <http://www.gnu.org/licenses/>.

\*---------------------------------------------------------------------------*/

Info<< nl
	<< "FAST-FC was developed by and is Copyright 2015, David B. Harvey" << nl
	<< "    " << nl
	<< "    " << nl
    << "FAST-FC was developed with sponsorship by the United States Department of Energy" << nl
	<< "and by support provided by Ballard Power Systems Inc." << nl
	<< "    " << nl
	<< "FAST-FC is free software: you can redistribute it and/or modify it" << nl
    << "under the terms of the GNU General Public License as published by" << nl
	<< "the Free Software Foundation, either version 3 of the License, or" << nl
	<< "(at your option) any later version." << nl
	<< "    " << nl
	<< "FC-APOLLO is a derivative work of FAST-FC, by David B. Harvey" << nl
	<< "    " << nl
	<<	"FC-APOLLO is distributed in the hope that it will be useful, but WITHOUT" << nl
	<< "ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or" << nl
	<< "FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License" << nl
	<< "for more details." << nl
	<< "    " << nl
	<< "You should have received a copy of the GNU General Public License" << nl
	<< "along with FC-APOLLO.  If not, see <http://www.gnu.org/licenses/>." << nl
	<< "    "  << nl
	<< "foam-extend is free software: you can redistribute it and/or modify it" << nl
    << "under the terms of the GNU General Public License as published by" << nl
	<< "the Free Software Foundation, either version 3 of the License, or" << nl
	<< "(at your option) any later version." << nl
	<< "    " << nl
	<< "foam-extend is distributed in the hope that it will be useful, but WITHOUT" << nl
	<< "ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or" << nl
	<< "FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License" << nl
	<< "for more details." << nl
	<< "    " << nl
	<< "You should have received a copy of the GNU General Public License" << nl
	<< "along with foam-extend.  If not, see <http://www.gnu.org/licenses/>." << nl
	<< endl;

Info<< nl
	<< "    " << nl
	<< "    " << nl
	<< "    " << nl
	<< "FAST-FC VERSION 0.0.3" << nl
	<< "Brought to you by openESS" << nl
	<< "June 30, 2015" << nl
	<< "    " << nl
	<< "    " << nl
	<< "    " << nl
	<< "/********************************* RUN RESULTS *********************************/ "
	<< endl;
