// Assign any Dimensioned Scalars for input values or field initialisation
dimensionedScalar	condElectron_ACL(transportProperties.lookup("condElectron"));
dimensionedScalar	condProton_ACL(transportProperties.lookup("condProton"));
dimensionedScalar	exchCurrBV_ACL(transportProperties.lookup("exchCurrentBV"));
dimensionedScalar	exchCurrTV_ACL(transportProperties.lookup("exchCurrentTV"));
dimensionedScalar	exchCurrHV_ACL(transportProperties.lookup("exchCurrentHV"));
dimensionedScalar	torSuppX_ACL(transportProperties.lookup("tortuositySuppX"));
dimensionedScalar	torSuppY_ACL(transportProperties.lookup("tortuositySuppY"));
dimensionedScalar	torSuppZ_ACL(transportProperties.lookup("tortuositySuppZ"));
dimensionedScalar	torIonX_ACL(transportProperties.lookup("tortuosityIonX"));
dimensionedScalar	torIonY_ACL(transportProperties.lookup("tortuosityIonY"));
dimensionedScalar	torIonZ_ACL(transportProperties.lookup("tortuosityIonZ"));

