#!/bin/sh
#cd ${0%/*} || exit 1    # run from this directory
#cd $PWD || exit 1
set -ue
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

echo
echo -e "\e[1;34m---------- Setting up the case files ----------\e[0m"
echo

# Test if directory location is valid
if [[ ! -d $PWD/constant || ! -d $PWD/system ]]
	then
	{
		echo "Current Path is not a valid case file"
		echo
		echo -e "\e[1;34m----------     ::ERROR::     ----------\e[0m"
		echo
	   	exit 1;
	}
	else
	{
		if [[ $PWD != *run* ]]
		then
		{
			echo "Current case directory is not within $FOAM_RUN"
			echo
		echo -e "\e[1;34m----------     ::ERROR::     ----------\e[0m"
			echo
	   		exit 1;
		}
		fi
	}
fi
# Create the default initial variables
echo
echo "Extracting the initial varaibles into 0/"
cp 0/init/* 0/.
echo "Done"
echo
# Create the mesh
echo "Creating the mesh:"
runApplication blockMesh
echo "Done"
echo
# Run setSet
echo "Creating Cell Sets from the initial mesh:"
runApplication setSet -batch makeCellSets.setSet
echo "Done"
echo
# Create the zones 
echo "Creating the Zones from the Sets:"
runApplication setsToZones -noFlipMap
echo "Done"
echo
# Create the divided and addressed mesh
echo "Splitting the mesh into regions based on the cell sets:"
runApplication splitMeshRegions -cellZones -overwrite
echo "Done"
echo

# Apply the boundary Conditons
echo "Applying the boundary conditions and initial field values for:"
while read line
do
	echo -ne $line " "
	for i in $line
	do
		changeDictionary -region $i > log.changeDictionary.$i 2>&1
	done
done <regions.lst
# inform user that the process is complete
echo
echo
echo -e "\e[1;34m---------- Case setup complete ----------\e[0m"
echo
ls -C --color=auto *
echo
# ----------------------------------------------------------------- end-of-file
