#!/bin/sh
#cd ${0%/*} || exit 1    # run from this directory
set -ue
# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions
# Clean the logs
echo
echo -e "\e[1;34m---------- Clean the case file ----------\e[0m"
echo

# Test if directory location is valid
if [[ ! -d $PWD/constant || ! -d $PWD/system ]]
	then
	{
		echo "Current Path is not a valid case file"
		echo
		echo -e "\e[1;34m----------     ::ERROR::     ----------\e[0m"
		echo
	   	exit 1;
	}
	else
	{
		if [[ $PWD != *run* ]]
		then
		{
			echo "Current case directory is not within $FOAM_RUN"
			echo
			echo -e "\e[1;34m----------     ::ERROR::     ----------\e[0m"
			echo
	   		exit 1;
		}
		fi
	}
fi

# Check if .fastfc exists
if [[ ! -d $PWD/.fastfc ]]; then 
	mkdir -p $PWD/.fastfc;  
fi
caseFlag=0;
# protect the case file
if stat -t *.cas >/dev/null 2>&1; 
	then
	{
		mv -v *.cas .fastfc/.
		cleanCase
		mv -v $PWD/.fastfc/*.cas .
	}
	else
	{
		cleanCase
	}
fi
# Clean the mesh and associated addressing files
echo
echo "Cleaning mesh and mesh addressing:"
rm -rf constant/cellToRegion constant/polyMesh/sets constant/polyMesh/boundary
rm -rf 0/cellToRegion
while read line
do
	echo -ne $line " "
	for i in $line
	do
		rm -rf constant/$i/polyMesh
	done
done <regions.lst
echo
# Clean the dictionary files placed into 0/
echo "Cleaning applied boundary conditions and initial fields:"
while read line
do
	echo -ne $line " "
	for i in $line
	do
		rm -rf 0/$i || true
	done
done <regions.lst
echo
echo "Cleaning the default variables fields:"
while read line
do
	echo -ne $line " "
	for i in $line
	do
		if [[ -f 0/$i ]]; then
			rm -f 0/$i 
		fi
	done
done <variables.lst
echo
echo "done"
echo
# Clean the parallel decomposition files in the subdomains
echo "Cleaning any parallel instructions from the subdomain in system/"
while read line
do
	echo -ne $line " "
	for i in $line
	do
		if [[ -f system/$i/decomposeParDict ]]; then
			rm -f system/$i/decomposeParDict
		fi
	done
done <regions.lst
echo "done"
echo
# Clean the previous run data, note this was done with the cleanCase command
echo "Cleaning previous run data:"
rm -rf 0/ccx 0/ccy 0/ccz
rm -rf polarizationData.txt
echo "done"
echo
# Clean the post processing files
echo "Cleaning post processing files:"
rm -rf VTK
rm -rf *.foam
echo "done"
echo
# Message that the clean process is finished
echo -e "\e[1;34m---------- Cleaning complete ----------\e[0m"
echo
ls -C --color=auto *
echo
# ----------------------------------------------------------------- end-of-file
