#!/bin/sh
#cd ${0%/*} || exit 1    # run from this directory
set -e
# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

echo -e "\e[1;34m---------- Clean the previous run data ----------\e[0m"
echo
# Test if directory location is valid
if [[ ! -d $PWD/constant || ! -d $PWD/system ]]
	then
	{
		echo "Current Path is not a valid case file"
		echo
		echo -e "\e[1;34m----------     ::ERROR::     ----------\e[0m"
		echo
	   	exit 1;
	}
	else
	{
		if [[ $PWD != *run* ]]
		then
		{
			echo "Current case directory is not within $FOAM_RUN"
			echo
		echo -e "\e[1;34m----------     ::ERROR::     ----------\e[0m"
			echo
	   		exit 1;
		}
		fi
	}
fi

# Check if .fastfc exists
if [[ ! -d $PWD/.fastfc ]]; then 
	mkdir -p $PWD/.fastfc;  
fi
caseFlag=0;
# protect the case file
if stat -t *.cas >/dev/null 2>&1; 
	then
	{
		mv -v *.cas .fastfc/.
		cleanTimeDirectories
		rm -rf processor* > /dev/null 2>&1
		mv -v $PWD/.fastfc/*.cas .
	}
	else
	{
		cleanTimeDirectories
		rm -rf processor* > /dev/null 2>&1
	}
fi

echo
# Clean the logs
rm -rf log.*Solver*
# Clean the post processing files
echo "Cleaning post processing files:"
echo -ne ".vtk"
echo -ne ","
rm -rf VTK
echo -ne " .foam"
rm -rf *.foam
echo
# Message that the clean process is finished
echo -e "\e[1;34m---------- Cleaning complete ----------\e[0m"
echo
ls -C --color=auto *
echo
# ----------------------------------------------------------------- end-of-file
