#!/bin/sh
#cd ${0%/*} || exit 1    # run from this directory
set -ue
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
# Decompose the domain for parallel
echo
echo -e "\e[1;34m---------- Decompose for parallel ----------\e[0m"
# Test if directory location is valid
if [[ ! -d $PWD/constant || ! -d $PWD/system ]]
	then
	{
		echo "Current Path is not a valid case file"
		echo
		echo -e "\e[1;34m----------     ::ERROR::     ----------\e[0m"

		echo
	   	exit 1;
	}
	else
	{
		if [[ $PWD != *run* ]]
		then
		{
			echo "Current case directory is not within $FOAM_RUN"
			echo
		echo -e "\e[1;34m----------     ::ERROR::     ----------\e[0m"

			echo
	   		exit 1;
		}
		fi
	}
fi

if [[ ! -f hosts.lst ]]; then
{
	echo "hosts.lst is necessary for domain decomposition, exiting..."
	echo
	echo -e "\e[1;34m----------     ::ERROR::     ----------\e[0m"
	echo "----------  Setting Proc Num ----------"
	exit 1;
}
else
{
	numProcessor=0;
	while read line
	do
		for i in $line
		do 
			numProcessor=$((numProcessor+1));
		done
	done < hosts.lst
}
fi

export fcParProcNum=$numProcessor

echo
echo "Distributing decomposeParDict to subdomains"
while read line
do
	for i in $line
	do
		echo -ne "      "$i
		cp system/decomposeParDict system/$i/.	
	done
done <regions.lst

echo
echo "decomposing the multi-domain mesh for parallel"
decomposePar -allRegions > log.decomposePar 2>&1
echo
echo -e "\e[1;34m---------- Decomposition Complete ----------\e[0m"
echo

# ----------------------------------------------------------------- end-of-file
