#!/bin/sh
#cd ${0%/*} || exit 1    # run from this directory
set -ue
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

echo -e "\e[1;34m---------- Checking the mesh quality ----------\e[0m"
echo
# Test if directory location is valid
if [[ ! -d $PWD/constant || ! -d $PWD/system ]]
	then
	{
		echo "Current Path is not a valid case file"
		echo
		echo -e "\e[1;34m----------     ::ERROR::     ----------\e[0m"
		echo
	   	exit 1;
	}
	else
	{
		if [[ $PWD != *run* ]]
		then
		{
			echo "Current case directory is not within $FOAM_RUN"
			echo
			echo -e "\e[1;34m----------     ::ERROR::     ----------\e[0m"
			echo
	   		exit 1;
		}
		fi
	}
fi

echo "Checking component meshes"
echo
while read line
do
	for i in $line
	do
		echo -ne "    " $i
		checkMesh -allGeometry -region $i > log.checkMesh.$i 2>&1
	done
done <regions.lst

while read line
do
	for i in $line
	do
		while read line; do echo "$line"; done < log.checkMesh.$i
		echo
	done
done <regions.lst
echo
echo "done"
echo
echo -e "\e[1;34m---------- Completed checking mesh quality ----------\e[0m"

# ----------------------------------------------------------------- end-of-file
