#!/bin/sh
#cd ${0%/*} || exit 1    # run from this directory
set -ue
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

echo -e "\e[1;34m---------- Create visualisation formats ----------\e[0m"
echo
# Test if directory location is valid
if [[ ! -d $PWD/constant || ! -d $PWD/system ]]
	then
	{
		echo "Current Path is not a valid case file"
		echo
		echo -e "\e[1;34m----------     ::ERROR::     ----------\e[0m"
		echo
	   	exit 1;
	}
	else
	{
		if [[ $PWD != *run* ]]
		then
		{
			echo "Current case directory is not within $FOAM_RUN"
			echo
			echo -e "\e[1;34m----------     ::ERROR::     ----------\e[0m"
			echo
	   		exit 1;
		}
		fi
	}
fi

echo "Creating VTK files for paraview post-processing"
echo
while read line
do
	for i in $line
	do
		echo -ne "    " $i
		foamToVTK -noZero -region $i > log.foamToVTK.$i 2>&1
	done
done < regions.lst
echo
echo "done"
echo
echo "Creating paraFoam files for post-processing"
echo
 
echo
echo "done"
echo
echo -e "\e[1;34m---------- Completed creating visualisation formats ----------\e[0m"

# ----------------------------------------------------------------- end-of-file
