#!/bin/sh
#cd ${0%/*} || exit 1    # run from this directory
set -ue
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
clear
echo
echo -e "\e[1;34m---------- Executing serial run ----------\e[0m"
echo
# Test if directory location is valid
if [[ ! -d $PWD/constant || ! -d $PWD/system ]]
	then
	{
		echo "Current Path is not a valid case file"
		echo
		echo -e "\e[1;34m----------     ::ERROR::     ----------\e[0m"
		echo
	   	exit 1;
	}
	else
	{
		if [[ $PWD != *run* ]]
		then
		{
			echo "Current case directory is not within $FOAM_RUN"
			echo
			echo -e "\e[1;34m----------     ::ERROR::     ----------\e[0m"
			echo
	   		exit 1;
		}
		fi
	}
fi

fcMonitor &
echo
runApplication `getApplication` 

echo
echo -e "\e[1;34m---------- completed serial run ----------\e[0m"
echo
ls -C --color=auto *
echo
# ----------------------------------------------------------------- end-of-file
