/*---------------------------------------------------------------------------*\
    F ast           	    | FAST-FC: 
	is the		            | The Open Source Analysis and Simulation Toolbox 
    A nalysis and           | for Fuel Cells
	S imulation		        |
	Toolbox for		        | Copyright 2015, David B. Harvey
	F uel                   |         
	C ells                  |                     
-------------------------------------------------------------------------------
License
	This file is part of FAST-FC.
   
	This file must be included in the main program and it is a violation of
	the license to remove it from the contents or from the 
	main program.

	FAST-FC is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    FAST-FC is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with FAST-FC.  If not, see <http://www.gnu.org/licenses/>.

\*---------------------------------------------------------------------------*/

Info<< nl
	<< "FAST-FC was developed by David B. Harvey, Copyright 2016." << nl
	<< "    " << nl
    << "FAST-FC was developed through sponsorship by the United States" << nl
	<< "Department of Energy, Ballard Power Systems Inc., and Queen's University" << nl
	<< "at Kingston" << nl
	<< "    " << nl
	<< "FC-APOLLO is a fork of FAST-FC and a derivative code by David B. Harvey" << nl
	<< "    " << nl
	<< "FAST-FC and FC-APOLLO are free software: you can redistribute them" << nl
	<< "and/or modify them under the terms of the GNU General Public License as" << nl 
	<< "published by the Free Software Foundation, either version 3 of the" << nl
	<< "License, or (at your option) any later version." << nl
	<< "    " << nl
	<< "FAST-FC and FC-APOLLO are distributed in the hope that they will be" << nl
	<< "useful, but WITHOUT ANY WARRANTY; without even the implied warranty" << nl
	<< "of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU" << nl
	<< "General Public License for more details." << nl
	<< "    " << nl
	<< "You should have received a copy of the GNU General Public License along" << nl
	<< "with FAST-FC and FC-APOLLO.  If not, see <http://www.gnu.org/licenses/>." << nl
	<< "    "  << nl
	<< "foam-extend is free software: you can redistribute it and/or modify it" << nl
    << "under the terms of the GNU General Public License as published by" << nl
	<< "the Free Software Foundation, either version 3 of the License, or" << nl
	<< "(at your option) any later version." << nl
	<< "    " << nl
	<< "foam-extend is distributed in the hope that it will be useful, but WITHOUT" << nl
	<< "ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or" << nl
	<< "FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License" << nl
	<< "for more details." << nl
	<< "    " << nl
	<< "You should have received a copy of the GNU General Public License" << nl
	<< "along with foam-extend.  If not, see <http://www.gnu.org/licenses/>." << nl
	<< endl;

Info<< nl
	<< "    " << nl
	<< "    " << nl
	<< "    " << nl
	<< "FAST-FC, Fast is an Analysis and Simulation Toolbox for Fuel Cell" << nl
	<< "FAST-FC is proudly brought to you by FAST Simulations" << nl
	<< "Visit us at <http://www.fastfc.com>."
	<< "    " << nl
	<< "    " << nl
	<< "    " << nl
	<< "/********************************* RUN RESULTS *********************************/ "
	<< endl;
