// Assign any Dimensioned Scalars for input values or field initialisation
dimensionedScalar condElectronCarbFibInput_APTL(transportProperties.lookup("condElectronCarbonFiber"));
dimensionedScalar volFPoreBOLInput_APTL(transportProperties.lookup("volFractPore"));
dimensionedScalar torPoreXInput_APTL(transportProperties.lookup("tortuosityPoreX"));
dimensionedScalar torPoreYInput_APTL(transportProperties.lookup("tortuosityPoreY"));
dimensionedScalar torPoreZInput_APTL(transportProperties.lookup("tortuosityPoreZ"));
dimensionedScalar torCarbFibXInput_APTL(transportProperties.lookup("tortuosityCarbonFiberX"));
dimensionedScalar torCarbFibYInput_APTL(transportProperties.lookup("tortuosityCarbonFiberY"));
dimensionedScalar torCarbFibZInput_APTL(transportProperties.lookup("tortuosityCarbonFiberZ"));
dimensionedScalar dryPermXInput_APTL(transportProperties.lookup("dryPermeabilityX"));
dimensionedScalar dryPermYInput_APTL(transportProperties.lookup("dryPermeabilityY"));
dimensionedScalar dryPermZInput_APTL(transportProperties.lookup("dryPermeabilityZ"));
dimensionedScalar condThermalCarbFibInput_APTL(transportProperties.lookup("condThermalCarbonFiber"));
dimensionedScalar contactAngleInput_APTL(transportProperties.lookup("contactAngle"));
dimensionedScalar condRateInput_APTL(transportProperties.lookup("condensationRate"));
dimensionedScalar evapRateInput_APTL(transportProperties.lookup("evaporationRate"));
dimensionedScalar sCorrOrderPermInput_APTL(transportProperties.lookup("sCorrectOrderPerm"));
dimensionedScalar sCorrOrderDiffInput_APTL(transportProperties.lookup("sCorrectOrderDiff"));
