// Assign any Dimensioned Scalars for input values or field initialisation
dimensionedScalar	condElectron_CCL(transportProperties.lookup("condElectron"));
dimensionedScalar	condProton_CCL(transportProperties.lookup("condProton"));
dimensionedScalar	exchCurrBV_CCL(transportProperties.lookup("exchCurrentBV"));
dimensionedScalar	torSuppX_CCL(transportProperties.lookup("tortuositySuppX"));
dimensionedScalar	torSuppY_CCL(transportProperties.lookup("tortuositySuppY"));
dimensionedScalar	torSuppZ_CCL(transportProperties.lookup("tortuositySuppZ"));
dimensionedScalar	torIonX_CCL(transportProperties.lookup("tortuosityIonX"));
dimensionedScalar	torIonY_CCL(transportProperties.lookup("tortuosityIonY"));
dimensionedScalar	torIonZ_CCL(transportProperties.lookup("tortuosityIonZ"));
