// Assign any Dimensioned Scalars for input values or field initialisation
dimensionedScalar condElectronCarbFibInput_CPTL(transportProperties.lookup("condElectronCarbonFiber"));
dimensionedScalar volFPoreBOLInput_CPTL(transportProperties.lookup("volFractPore"));
dimensionedScalar torPoreXInput_CPTL(transportProperties.lookup("tortuosityPoreX"));
dimensionedScalar torPoreYInput_CPTL(transportProperties.lookup("tortuosityPoreY"));
dimensionedScalar torPoreZInput_CPTL(transportProperties.lookup("tortuosityPoreZ"));
dimensionedScalar torCarbFibXInput_CPTL(transportProperties.lookup("tortuosityCarbonFiberX"));
dimensionedScalar torCarbFibYInput_CPTL(transportProperties.lookup("tortuosityCarbonFiberY"));
dimensionedScalar torCarbFibZInput_CPTL(transportProperties.lookup("tortuosityCarbonFiberZ"));
dimensionedScalar dryPermXInput_CPTL(transportProperties.lookup("dryPermeabilityX"));
dimensionedScalar dryPermYInput_CPTL(transportProperties.lookup("dryPermeabilityY"));
dimensionedScalar dryPermZInput_CPTL(transportProperties.lookup("dryPermeabilityZ"));
dimensionedScalar condThermalCarbFibInput_CPTL(transportProperties.lookup("condThermalCarbonFiber"));
dimensionedScalar contactAngleInput_CPTL(transportProperties.lookup("contactAngle"));
dimensionedScalar condRateInput_CPTL(transportProperties.lookup("condensationRate"));
dimensionedScalar evapRateInput_CPTL(transportProperties.lookup("evaporationRate"));
dimensionedScalar sCorrOrderPermInput_CPTL(transportProperties.lookup("sCorrectOrderPerm"));
dimensionedScalar sCorrOrderDiffInput_CPTL(transportProperties.lookup("sCorrectOrderDiff"));
